# Generated by Django 5.2.11 on 2026-02-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='assessments_answer',
        ),
        migrations.AlterModelTable(
            name='personalityprofile',
            table='assessments_personalityprofile',
        ),
        migrations.AlterModelTable(
            name='question',
            table='assessments_question',
        ),
        migrations.AlterModelTable(
            name='test',
            table='assessments_test',
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='assessments_testresult',
        ),
    ]
