# Generated by Django 5.2.11 on 2026-02-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_testresult_expires_at_testresult_is_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('policy_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_consents', to='assessments.test')),
            ],
            options={
                'db_table': 'assessments_guestconsentlog',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
